### ISSUE TITLE
Configs which use `include` are always flagged as invalid.

### ISSUE THREAD

**Issue by RamonGebben** [BuBuaBu/gitlab-ci-lint#19]
## How to reproduce

Create a "template" job e.g.

```yml
.job_template:
  image: node:12
  stage: test
  script:
    - yarn test
```
`include` in within your `.gitlab-ci.yml`

```yml
include: "/templates/test.yml"

stages:
  - test

unit_test:
  extends: .job_template
```
Run linter against `.gitlab-ci.yml`
